Fix UpdateResultsAPI duplicate record issue
kruize/autotune pull request #1051
Opened 2023-11-21 10:15 UTC by khansaad

This PR fixes the duplicate record mismatch issue after hitting the updateResults API. We were seeing a difference in the number of records getting saved in the DB.

2023-11-21 11:13 UTC, dinogun commented
@khansaad as mentioned we need to add the appropriate negative tests to handle this scenario. @chandrams please review

2023-11-21 13:15 UTC, msvinaykumar approved these changes

2023-11-21 20:33 UTC, chandrams requested changes

2023-11-21 20:33 UTC, chandrams commented on tests/scripts/remote_monitoring_tests/rest_apis/test_update_results.py
> +    assert data['message'] == UPDATE_RESULTS_FAILED_RECORDS_MSG
Also validate the failed records data error messages - "An entry for this record already exists!"

2023-11-22 07:26 UTC, chandrams commented on tests/scripts/remote_monitoring_tests/rest_apis/test_update_results.py
> +    assert DUPLICATE_RECORDS_MSG in error_messages
We need to validate each error message or http code and use equals here

2023-11-22 07:26 UTC, chandrams commented on tests/scripts/remote_monitoring_tests/rest_apis/test_update_results.py
> +    response = list_experiments("true", None, "false", experiment_name)
Assign the values to variables and pass those variables for better readability. Also update any other references to list_experiments in other tests.

2023-11-22 11:15 UTC, chandrams approved these changes
LGTM

2023-11-23 08:55 UTC, merged