Refactor Bulk Job Manager to call createExperiments API
kruize/autotune pull request #1337
Opened 2024-10-09 09:21 UTC by khansaad

## Description

This PR refactors the bulk job manager to call the createExperiments API for experiment creation replacing redundant code for adding new experiments.

Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] New feature
- [ ] Docs update
- [ ] Breaking change (What changes might users need to make in their application due to this PR?)
- [ ] Requires DB changes

## How has this been tested? Testing in-progress

Please describe the tests that were run to verify your changes and steps to reproduce. Please specify any test configuration required. 

- [ ] New Test X
- [ ] Functional testsuite

**Test Configuration**
* Kubernetes clusters tested on: 

## Checklist :dart:

- [ ] Followed coding guidelines
- [ ] Comments added
- [ ] Dependent changes merged
- [ ] Documentation updated
- [ ] Tests added or updated

## Additional information

Include any additional information such as links, test results, screenshots here

2024-10-09 11:23 UTC, khansaad commented
Local monitoring demo works fine now.
Bulk demo is failing due to a datasource issue, fixing that.

2024-10-10 08:06 UTC, dinogun commented
@khansaad Would be good if you can rebase this on top of PR #1332

2024-10-10 12:06 UTC, msvinaykumar commented on src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
> +                                    if (responseCode == HttpURLConnection.HTTP_CREATED) {
If experiments already created then also Please add it to 
createExperimentAPIObjectMap.put(jsonObject.get("experiment_name").getAsString(), `createExperimentAPIObject);`




avoid Failed one like JOB experiments etc

2024-10-10 12:12 UTC, msvinaykumar commented on src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
> +        URL url;
Can we make use of GenericRestAPIClient Class Please see if this can be used for geenratingrecommendations URL too

2024-10-10 12:16 UTC, msvinaykumar commented on src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
> +            connection = (HttpURLConnection) url.openConnection();
Please make use of GenericResTAPI class and same for generating recommendations

2024-10-10 12:22 UTC, msvinaykumar requested changes
I think there is slight confusion here
 CREATE_EXPERIMENT_CONFIG_BEAN is created to hold defaults and it acts as a template and Constant
 and 
 
 ContainerAPIObject containerAPIObject should get created using those CREATE_EXPERIMENT_CONFIG_BEAN constants
 
 and avoid this conversions 
 
 String createExpJSON = prepareCreateExperimentJSONInput(dc, dsc, dsw, namespace,
                                            experiment_name, this.bulkInput.getDatasource());
                                            
  example
  
```
CreateExperimentAPIObject createExperimentAPIObject = new CreateExperimentAPIObject();
                                    createExperimentAPIObject.setMode(CREATE_EXPERIMENT_CONFIG_BEAN.getMode());
                                    createExperimentAPIObject.setTargetCluster(CREATE_EXPERIMENT_CONFIG_BEAN.getTarget());
                                    createExperimentAPIObject.setApiVersion(CREATE_EXPERIMENT_CONFIG_BEAN.getVersion());
                                    String experiment_name = this.bulkInput.getDatasource() + "|" + dsc.getDataSourceClusterName() + "|" + namespace.getDataSourceNamespaceName()
                                            + "|" + dsw.getDataSourceWorkloadName() + "(" + dsw.getDataSourceWorkloadType() + ")" + "|" + dc.getDataSourceContainerName();
                                    createExperimentAPIObject.setExperimentName(experiment_name);
                                    createExperimentAPIObject.setDatasource(this.bulkInput.getDatasource());
                                    createExperimentAPIObject.setClusterName(dsc.getDataSourceClusterName());
                                    createExperimentAPIObject.setPerformanceProfile(CREATE_EXPERIMENT_CONFIG_BEAN.getPerformanceProfile());
                                    List<KubernetesAPIObject> kubernetesAPIObjectList = new ArrayList<>();
                                    KubernetesAPIObject kubernetesAPIObject = new KubernetesAPIObject();
                                    ContainerAPIObject cao = new ContainerAPIObject(dc.getDataSourceContainerName(),
                                            dc.getDataSourceContainerImageName(), null, null);
                                    kubernetesAPIObject.setContainerAPIObjects(Arrays.asList(cao));
                                    kubernetesAPIObject.setName(dsw.getDataSourceWorkloadName());
                                    kubernetesAPIObject.setType(dsw.getDataSourceWorkloadType());
                                    kubernetesAPIObject.setNamespace(namespace.getDataSourceNamespaceName());
                                    kubernetesAPIObjectList.add(kubernetesAPIObject);
                                    createExperimentAPIObject.setKubernetesObjects(kubernetesAPIObjectList);
                                    RecommendationSettings rs = new RecommendationSettings();
                                    rs.setThreshold(CREATE_EXPERIMENT_CONFIG_BEAN.getThreshold());
                                    createExperimentAPIObject.setRecommendationSettings(rs);
                                    TrialSettings trialSettings = new TrialSettings();
                                    trialSettings.setMeasurement_durationMinutes(CREATE_EXPERIMENT_CONFIG_BEAN.getMeasurementDurationStr());
                                    createExperimentAPIObject.setTrialSettings(trialSettings);
                                    List<KruizeObject> kruizeExpList = new ArrayList<>();

                                    createExperimentAPIObject.setExperiment_id(Utils.generateID(createExperimentAPIObject.toString()));
                                    createExperimentAPIObject.setStatus(AnalyzerConstants.ExperimentStatus.IN_PROGRESS);
                                    createExperimentAPIObject.setExperimentType(AnalyzerConstants.ExperimentTypes.CONTAINER_EXPERIMENT);
                                         
```                



// Convert to JSON
        ObjectMapper mapper = new ObjectMapper();
        String json = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(createExperimentAPIObject);

2024-10-11 12:04 UTC, dinogun commented
@khansaad Please update the local_monitoring and bulk API test results here, thanks

2024-10-11 15:28 UTC, khansaad commented
> @khansaad Please update the local_monitoring and bulk API test results here, thanks

LM Demo Response: https://privatebin.corp.redhat.com/?21d205a6bba724fd#2sFryeAfKVW9zf5m2a4NjNU1USJxwhEMEqPDn4ubcVnA

Bulk Demo Response: https://privatebin.corp.redhat.com/?2ec351fb611c5918#HSo15gBk1JfpcA2B1LiCTwAKUsSvEznQK58kFWFX7MKE

Jenkins run for the same :
https://ci.app-svc-perf.corp.redhat.com/job/ExternalTeams/job/Autotune/job/kruize_local_release_tests/4/

2024-10-11 15:37 UTC, khansaad commented
Added the demo results and the local monitoring demo test results

2024-10-14 10:20 UTC, dinogun commented on src/main/java/com/autotune/common/datasource/DataSourceMetadataOperator.java
>                  LOGGER.info("uniquekey: {}", uniqueKey);
This should be LOGGER.debug

2024-10-14 10:22 UTC, dinogun commented on src/main/java/com/autotune/utils/GenericRestApiClient.java
> +            LOGGER.info("Executing Prometheus metrics request: {}", httpRequestBase.getRequestLine());
Please evaluate all LOGGER statements to see if they should really be `info` or `debug`

2024-10-14 10:31 UTC, dinogun commented on src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
> +                                if (experiment_name.contains(AnalyzerConstants.K8sObjectConstants.Types.JOB)) {
Please add a comment here if `JOB` type applications are handled differently

2024-10-15 07:14 UTC, khansaad commented on src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
> +                                if (experiment_name.contains(AnalyzerConstants.K8sObjectConstants.Types.JOB)) {
Done

2024-10-15 08:42 UTC, dinogun approved these changes
LGTM

2024-10-15 08:57 UTC, msvinaykumar commented on src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
> +                                    // if the experiment is successfully created, add it in the map
if duplicate experiments then also add it to createExperimentAPIObject
if it failed then it should be mentioned in JOB details

2024-10-15 09:01 UTC, msvinaykumar commented on src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
> +                                    // if the experiment is successfully created, add it in the map
here failed one should get handled
jobData.getData().getExperiments().setFailedExperiments

2024-10-15 09:04 UTC, msvinaykumar commented on src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
> +                                if (experiment_name.contains(AnalyzerConstants.K8sObjectConstants.Types.JOB)) {
This conditions should be removed as failed already handled above during createExperiment APU

2024-10-15 12:26 UTC, msvinaykumar approved these changes
LGTM

2024-10-15 13:19 UTC, merged