Add hpo_algo_impl and step
kruize/autotune pull request #193
Opened 2021-03-02 08:05 UTC by ShishirH

Signed-off-by: Shishir Halaharvi <shalahar@redhat.com>

2021-03-02 08:05 UTC, ShishirH commented
YAML and code changes to add hpo_algo_impl and step

2021-03-02 12:30 UTC, ShishirH commented on manifests/autotune-config-crd.yaml
> +                  description: 'Step of the tunable'
In the code, yes. Right now there are no default values. Yes, we will need to update all the autotune-config yamls and add steps

2021-03-04 15:07 UTC, dinogun requested changes

2021-03-04 15:07 UTC, dinogun commented on src/main/java/com/autotune/dependencyAnalyzer/k8sObjects/SlaInfo.java
> +		this.hpoAlgoImpl = hpoMlImpl;
Same for the Algo, if nothing is set, then we have to set `optuna_tpe`.

2022-01-21 12:58 UTC, dinogun commented
This PR is now no longer required

2022-01-21 12:58 UTC, closed without merging