Tests to validate autotune layer config object id
kruize/autotune pull request #216
Opened 2021-03-25 06:39 UTC by shruacha1234

Signed-off-by: Shruthi <Shruthi.Acharya@ibm.com>

2021-04-16 05:54 UTC, chandrams commented
@shruacha1234 - can you update the readme too.

2021-05-19 11:18 UTC, chandrams requested changes

2021-05-19 11:18 UTC, chandrams commented on tests/README.md
> +  	2. Check if re-applying the autotune object without modifying yaml changes the autotune object id
Change this to - Check if re-applying the autotune object without modifying the yaml does not change the autotune object id

2021-05-19 11:18 UTC, chandrams commented on tests/autotune_test_yamls/manifests/da/autotune_config_id_test_yaml/new_layer_config_test/openj9-config.yaml
> +    upper_bound: '250M'
Upper bound and lower bound are now defined as double

2021-05-19 11:18 UTC, chandrams commented on tests/README.md
> +  - Modify the configmap yaml
You can add the scenario details here

2021-05-21 06:18 UTC, chandrams commented on tests/README.md
> +  	1. invalid-cluster-type
Start with caps

2021-05-21 06:18 UTC, chandrams commented on tests/README.md
> +  - Modify the configmap yaml
Change Modify to Modifies

2021-05-21 06:28 UTC, chandrams approved these changes
LGTM

2021-06-04 12:17 UTC, dinogun commented
Please resolve the conflicts for this PR

2021-06-17 11:03 UTC, dinogun commented
LGTM

2021-06-17 11:03 UTC, merged