Added createExperiment api doc
kruize/autotune pull request #273
Opened 2021-07-23 07:15 UTC by bharathappali

Signed-off-by: bharathappali <bharath.appali@gmail.com>

2021-08-04 05:23 UTC, chandrams requested changes

2021-09-01 05:32 UTC, bharathappali commented on design/API.md
> +deployment_tracking : Which deployments to track (either prod or training or both)
No the trackers section deals with deployments to track. Deployment policy is only to re deploy existing one or to deploy a new one

2021-09-01 05:32 UTC, bharathappali commented on design/API.md
> +below. The Input Json holds details of the configuration to try, settings to that particular deployment
Done

2021-09-01 05:33 UTC, bharathappali commented on design/API.md
> +total_duration : How long a trial experiment should run for ?
In markdown viewer i see it in a different line (IntelliJIDEA) lemme know if issue persists

2021-09-01 05:33 UTC, bharathappali commented on design/API.md
> +`curl -H 'Accept: application/json' -d <INPUT JSON> http://<URL>:<PORT>/getTrialStatus`
Will make the changes

2021-09-01 05:34 UTC, bharathappali commented on design/API.md
> +`curl -H 'Accept: application/json' -d <INPUT JSON> http://<URL>:<PORT>/getTrialStatus`
currently its a get request only

2021-09-22 06:15 UTC, chandrams commented on design/API.md
> +      "state": "",
We need to remove state and result fields from input json as it will be part of output json from EM

2021-11-17 06:18 UTC, chandrams commented
@bharathappali - Can you please update the API design doc with latest changes for listTrialStatus API

2022-02-14 07:14 UTC, chandrams commented on design/API.md
> +            "warmup_duration": "1min",
@bharathappali - Format of duration isn't consistent, please correct it.

2023-03-01 13:09 UTC, dinogun commented
Closing as this is stale. Re-open if needed.

2023-03-01 13:09 UTC, closed without merging