359 Autotune logs have a lot of information being logged
kruize/autotune pull request #370
Opened 2021-12-28 06:29 UTC by msvinaykumar

Creating meaningful log would be essential to troubleshoot. And hence Autotune modules should implement effective logging and Error/Exception handler. I have introduced log4j2.properties files to customize logging behavior.
I have used console appender with following format
             %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
            Example : 
<pre>2021-12-28 05:52:38 DEBUG Config:730 - Found service account namespace at: [/var/run/secrets/kubernetes.io/serviceaccount/namespace].
2021-12-28 05:52:39 INFO  AutotuneDeploymentInfo:172 - Cluster Type: kubernetes
2021-12-28 05:52:39 INFO  AutotuneDeploymentInfo:173 - Kubernetes Type: minikube
2021-12-28 05:52:39 INFO  AutotuneDeploymentInfo:174 - Auth Type: 
2021-12-28 05:52:39 INFO  AutotuneDeploymentInfo:175 - Monitoring Agent: prometheus
2021-12-28 05:52:39 INFO  AutotuneDeploymentInfo:176 - Monitoring Agent URL: http://10.107.224.73:9090
2021-12-28 05:52:39 INFO  AutotuneDeploymentInfo:177 - Monitoring agent service: prometheus-k8s
</pre>

Regarding #359 Autotune logs have a lot of information being logged : This PR will remove information from external package.

Signed-off-by: Vinay Kumar Mysore Sathya Kumar <vinakuma@vinakuma.remote.csb>

2021-12-31 06:40 UTC, bharathappali commented
@msvinaykumar I see the commit signature is not verified and also the sign off address is `vinakuma@vinakuma.remote.csb`

Please add the gpg signing to the commit by amending it with `-S` and author as your username with Redhat email id

2021-12-31 07:57 UTC, bharathappali commented
Tested the PR. LGTM

sample log:
```
bharathappali@bharathappali-T590:~$ kubectl -n monitoring logs autotune-787fdbd9f7-l9f27 autotune
2021-12-31 07:39:57.592:INFO::main: Logging initialized @424ms to org.eclipse.jetty.util.log.StdErrLog
2021-12-31 07:39:57 DEBUG Config:520 - Trying to configure client from Kubernetes config...
2021-12-31 07:39:57 DEBUG Config:526 - Did not find Kubernetes config at: [/home/default/.kube/config]. Ignoring.
2021-12-31 07:39:57 DEBUG Config:452 - Trying to configure client from service account...
2021-12-31 07:39:57 DEBUG Config:457 - Found service account host and port: 10.96.0.1:443
2021-12-31 07:39:57 DEBUG Config:463 - Found service account ca cert at: [/var/run/secrets/kubernetes.io/serviceaccount/ca.crt].
2021-12-31 07:39:57 DEBUG Config:470 - Found service account token at: [/var/run/secrets/kubernetes.io/serviceaccount/token].
2021-12-31 07:39:57 DEBUG Config:725 - Trying to configure client namespace from Kubernetes service account namespace path...
2021-12-31 07:39:57 DEBUG Config:730 - Found service account namespace at: [/var/run/secrets/kubernetes.io/serviceaccount/namespace].
2021-12-31 07:39:58 INFO  AutotuneDeploymentInfo:172 - Cluster Type: kubernetes
2021-12-31 07:39:58 INFO  AutotuneDeploymentInfo:173 - Kubernetes Type: minikube
2021-12-31 07:39:58 INFO  AutotuneDeploymentInfo:174 - Auth Type: 
2021-12-31 07:39:58 INFO  AutotuneDeploymentInfo:175 - Monitoring Agent: prometheus
2021-12-31 07:39:58 INFO  AutotuneDeploymentInfo:176 - Monitoring Agent URL: http://10.105.112.163:9090
2021-12-31 07:39:58 INFO  AutotuneDeploymentInfo:177 - Monitoring agent service: prometheus-k8s


2021-12-31 07:39:58 DEBUG Config:520 - Trying to configure client from Kubernetes config...
2021-12-31 07:39:58 DEBUG Config:526 - Did not find Kubernetes config at: [/home/default/.kube/config]. Ignoring.
2021-12-31 07:39:58 DEBUG Config:452 - Trying to configure client from service account...
2021-12-31 07:39:58 DEBUG Config:457 - Found service account host and port: 10.96.0.1:443
2021-12-31 07:39:58 DEBUG Config:463 - Found service account ca cert at: [/var/run/secrets/kubernetes.io/serviceaccount/ca.crt].
2021-12-31 07:39:58 DEBUG Config:470 - Found service account token at: [/var/run/secrets/kubernetes.io/serviceaccount/token].
2021-12-31 07:39:58 DEBUG Config:725 - Trying to configure client namespace from Kubernetes service account namespace path...
2021-12-31 07:39:58 DEBUG Config:730 - Found service account namespace at: [/var/run/secrets/kubernetes.io/serviceaccount/namespace].
2021-12-31 07:39:58 INFO  RawWatchConnectionManager:117 - Websocket opened
2021-12-31 07:39:58 INFO  RawWatchConnectionManager:117 - Websocket opened
2021-12-31 07:39:58 INFO  ExperimentManager:32 - EM version: testv1
2021-12-31 07:39:58 INFO  ExperimentManager:28 - Initializing EM
2021-12-31 07:39:58 INFO  ExperimentManager:71 - Adding EM Servlets
2021-12-31 07:39:58 INFO  EMExecutorService:30 - Creating regular executor
2021-12-31 07:39:58 INFO  EMExecutorService:34 - Creating scheduled executor
2021-12-31 07:39:58 INFO  EMExecutorService:67 - Starting stage processors
2021-12-31 07:39:58 INFO  EMExecutorService:67 - Starting stage processors
Waiting for experiments ... 
Adding Tunable: memoryRequest has bounds; ubv: 300.0 lbv: 150.0 ubu: Mi lbu: Mi
Adding Tunable: cpuRequest has bounds; ubv: 3.0 lbv: 1.0 ubu:  lbu: 
2021-12-31 07:39:58 INFO  AutotuneDeployment:157 - Added autotuneconfig container
Adding Tunable: MaxInlineLevel has bounds; ubv: 50.0 lbv: 9.0 ubu:  lbu: 
2021-12-31 07:39:58 INFO  AutotuneDeployment:157 - Added autotuneconfig hotspot
2021-12-31 07:39:58 DEBUG PrometheusDataSource:97 - Query URL is: http://10.105.112.163:9090/api/v1/query?query=jvm_memory_used_bytes%7Barea%3D%22heap%22%2C%7D
2021-12-31 07:39:58 DEBUG PrometheusDataSource:98 - Query response: {"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"jvm_memory_used_bytes","area":"heap","container":"galaxies","endpoint":"galaxies-port","id":"Eden Space","instance":"172.17.0.15:8080","job":"galaxies-service","namespace":"default","pod":"galaxies-sample-c7f764b6d-4fms8","service":"galaxies-service"},"value":[1640936398.277,"62080992"]},{"metric":{"__name__":"jvm_memory_used_bytes","area":"heap","container":"galaxies","endpoint":"galaxies-port","id":"Survivor Space","instance":"172.17.0.15:8080","job":"galaxies-service","namespace":"default","pod":"galaxies-sample-c7f764b6d-4fms8","service":"galaxies-service"},"value":[1640936398.277,"0"]},{"metric":{"__name__":"jvm_memory_used_bytes","area":"heap","container":"galaxies","endpoint":"galaxies-port","id":"Tenured Gen","instance":"172.17.0.15:8080","job":"galaxies-service","namespace":"default","pod":"galaxies-sample-c7f764b6d-4fms8","service":"galaxies-service"},"value":[1640936398.277,"9969608"]},{"metric":{"__name__":"jvm_memory_used_bytes","area":"heap","container":"petclinic-tomcat","endpoint":"petclinic-port","id":"nursery-allocate","instance":"172.17.0.16:8081","job":"petclinic-service","namespace":"default","pod":"petclinic-sample-6f47b9995f-vclw7","service":"petclinic-service"},"value":[1640936398.277,"33293640"]},{"metric":{"__name__":"jvm_memory_used_bytes","area":"heap","container":"petclinic-tomcat","endpoint":"petclinic-port","id":"nursery-survivor","instance":"172.17.0.16:8081","job":"petclinic-service","namespace":"default","pod":"petclinic-sample-6f47b9995f-vclw7","service":"petclinic-service"},"value":[1640936398.277,"13565952"]},{"metric":{"__name__":"jvm_memory_used_bytes","area":"heap","container":"petclinic-tomcat","endpoint":"petclinic-port","id":"tenured-LOA","instance":"172.17.0.16:8081","job":"petclinic-service","namespace":"default","pod":"petclinic-sample-6f47b9995f-vclw7","service":"petclinic-service"},"value":[1640936398.277,"0"]},{"metric":{"__name__":"jvm_memory_used_bytes","area":"heap","container":"petclinic-tomcat","endpoint":"petclinic-port","id":"tenured-SOA","instance":"172.17.0.16:8081","job":"petclinic-service","namespace":"default","pod":"petclinic-sample-6f47b9995f-vclw7","service":"petclinic-service"},"value":[1640936398.277,"27329112"]}]}}
2021-12-31 07:39:58 DEBUG PrometheusDataSource:108 - Applications for the query: [galaxies-sample-c7f764b6d-4fms8, galaxies-sample-c7f764b6d-4fms8, galaxies-sample-c7f764b6d-4fms8, petclinic-sample-6f47b9995f-vclw7, petclinic-sample-6f47b9995f-vclw7, petclinic-sample-6f47b9995f-vclw7, petclinic-sample-6f47b9995f-vclw7]
2021-12-31 07:39:58 DEBUG Config:520 - Trying to configure client from Kubernetes config...
2021-12-31 07:39:58 DEBUG Config:526 - Did not find Kubernetes config at: [/home/default/.kube/config]. Ignoring.
2021-12-31 07:39:58 DEBUG Config:452 - Trying to configure client from service account...
2021-12-31 07:39:58 DEBUG Config:457 - Found service account host and port: 10.96.0.1:443
2021-12-31 07:39:58 DEBUG Config:463 - Found service account ca cert at: [/var/run/secrets/kubernetes.io/serviceaccount/ca.crt].
2021-12-31 07:39:58 DEBUG Config:470 - Found service account token at: [/var/run/secrets/kubernetes.io/serviceaccount/token].
2021-12-31 07:39:58 DEBUG Config:725 - Trying to configure client namespace from Kubernetes service account namespace path...
2021-12-31 07:39:58 DEBUG Config:730 - Found service account namespace at: [/var/run/secrets/kubernetes.io/serviceaccount/namespace].
Adding Tunable: quarkus.thread-pool.core-threads has bounds; ubv: 10.0 lbv: 1.0 ubu:  lbu: 
Adding Tunable: quarkus.thread-pool.queue-size has bounds; ubv: 100.0 lbv: 1.0 ubu:  lbu: 
Adding Tunable: quarkus.hibernate-orm.jdbc.statement-fetch-size has bounds; ubv: 50.0 lbv: 1.0 ubu:  lbu: 
2021-12-31 07:39:58 INFO  AutotuneDeployment:157 - Added autotuneconfig quarkus
2021-12-31 07:39:58 DEBUG Config:520 - Trying to configure client from Kubernetes config...
2021-12-31 07:39:58 DEBUG Config:526 - Did not find Kubernetes config at: [/home/default/.kube/config]. Ignoring.
2021-12-31 07:39:58 DEBUG Config:452 - Trying to c [...]

2021-12-31 07:58 UTC, bharathappali approved these changes
LGTM

2022-01-04 14:47 UTC, msvinaykumar reviewed
wrong file committed

2022-01-10 14:09 UTC, dinogun commented
@msvinaykumar When I apply this PR, I am getting the following error. Is there some initialization missing perhaps? 
```
2022-01-10 13:53:31,547 main ERROR Unable to locate appender "consoleLogger " for logger config "root"
```

2022-01-12 09:06 UTC, chandrams commented
@msvinaykumar - As discussed, the tests look for these messages - com.autotune.analyzer.deployment.DeploymentInfo - Cluster type kube8 is not supported

And I see, this one when I tested yesterday:
2022-01-11 18:02:47 ERROR AutotuneDeploymentInfo:88 - Cluster type kube8 is not supported
com.autotune.analyzer.exceptions.ClusterTypeNotSupportedException

Will review it once you finalize on the message format.

2022-01-13 15:54 UTC, dinogun requested changes
@msvinaykumar Hi Vinay, looks like we need one more change in the autotune deployment [yaml](https://github.com/kruize/autotune/blob/master/manifests/autotune-operator-deployment.yaml_template) to pass the `ROOT_LOGGING_LEVEL` parameter to the application

2022-01-14 06:08 UTC, msvinaykumar commented
> @msvinaykumar Hi Vinay, looks like we need one more change in the autotune deployment [yaml](https://github.com/kruize/autotune/blob/master/manifests/autotune-operator-deployment.yaml_template) to pass the `ROOT_LOGGING_LEVEL` parameter to the application

Hello Dinakar I already did changes to following Yamls. are you referring to any other yaml
![image](https://user-images.githubusercontent.com/25493416/149459955-bcaf751d-3f1a-4e60-bf2d-ef6cb81548b9.png)

2022-01-18 11:12 UTC, chandrams commented on src/main/resources/log4j2.properties
> +#ConsoleAppenderwillprintlogsonconsole
Include a space after hash

2022-01-18 11:12 UTC, chandrams commented on src/main/resources/log4j2.properties
> +#pattern of the logs
Include a space after hash

2022-01-18 11:12 UTC, chandrams commented on src/main/resources/log4j2.properties
> +
Remove extra lines

2022-01-18 11:12 UTC, chandrams commented on src/main/resources/log4j2.properties
> +appender.console.name=consoleLogger
Spaces after equals - keep it consistent throughout the file

2022-01-18 13:57 UTC, chandrams commented
@msvinaykumar - You will need to update Analyzer code to use ROOT_LOGGING_LEVEL similar to LOGGING_LEVEL envs, look at InitializeDeployment.java

2022-01-20 12:23 UTC, chandrams commented on src/main/java/com/autotune/analyzer/deployment/InitializeDeployment.java
> +		AutotuneDeploymentInfo.setRootloggingLevel(root_logging_level);
Change Rootlogging to RootLogging and rootloggingLevel to rootLoggingLevel - in all places applicable

2022-01-20 12:23 UTC, chandrams commented on src/main/java/com/autotune/analyzer/deployment/AutotuneDeploymentInfo.java
> +	public static String getRootloggingLevel() {return rootloggingLevel;}
Move the return to next line to keep it consistent with getLoggingLevel()

2022-01-21 06:40 UTC, chandrams approved these changes
LGTM

2022-01-21 08:38 UTC, dinogun approved these changes
LGTM

2022-01-21 08:38 UTC, merged